#Dev Profile Configuration

# Application Configuration
spring.application.name=backend

# Server Port Configuration
server.port=${SERVER_PORT}

# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
spring.datasource.hikari.maximum-pool-size=${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE}
spring.datasource.hikari.minimum-idle=${SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE}
spring.datasource.hikari.idle-timeout=${SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT}
spring.datasource.hikari.max-lifetime=${SPRING_DATASOURCE_HIKARI_MAX_LIFETIME}
spring.datasource.hikari.connection-timeout=${SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT}

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Spring Data JPA Configuration
spring.data.web.pageable.one-indexed-parameters=true
spring.data.web.pageable.default-page-size=10

# JWT Security Configuration
jwt.base64-secret=${JWT_BASE64_SECRET}
jwt.access-token-validity-in-seconds=${JWT_ACCESS_TOKEN_VALIDITY_IN_SECONDS}
jwt.refresh-token-validity-in-seconds=${JWT_REFRESH_TOKEN_VALIDITY_IN_SECONDS}

# Springdoc Configuration
springdoc.swagger-ui.config-url=${SPRINGDOC_SWAGGER_UI_CONFIG_URL}
springdoc.swagger-ui.url=${SPRINGDOC_SWAGGER_UI_URL}
springdoc.api-docs.enabled=${SPRINGDOC_API_DOCS_ENABLED}
springdoc.swagger-ui.enabled=${SPRINGDOC_SWAGGER_UI_ENABLED}

# Swagger/API Documentation Configuration
swagger.server-url=${SWAGGER_SERVER_URL}
swagger.server-desc=${SWAGGER_SERVER_DESC}

# File Upload Configuration
spring.servlet.multipart.max-file-size=10485760
spring.servlet.multipart.max-request-size=104857600

# Redis (Spring Data Redis + Lettuce)
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.connect-timeout=${SPRING_DATA_REDIS_CONNECT_TIMEOUT}
spring.data.redis.lettuce.pool.max-active=${SPRING_DATA_REDIS_LETTUCE_POOL_MAX_ACTIVE}
spring.data.redis.lettuce.pool.max-idle=${SPRING_DATA_REDIS_LETTUCE_POOL_MAX_IDLE}
spring.data.redis.lettuce.pool.min-idle=${SPRING_DATA_REDIS_LETTUCE_POOL_MIN_IDLE}

# API Key Configuration
api.key=${API_KEY}

# Application Paths Configuration
spring.web.resources.static-locations=${SPRING_WEB_RESOURCES_STATIC_LOCATIONS}
app.base-url=${APP_BASE_URL}
app.upload-dir=${APP_UPLOAD_DIR}

# External Service URLs
backend.dotnet.url=https://peshop.tandat.site/dotnet-peshop
spring.boot.url=https://xjanua.me/spring-peshop

# ONLY in Dev
# Logging (SQL Debug)
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace

# Log File Path Configuration
app.log-file-traffic-path=${APP_LOG_FILE_TRAFFIC_PATH}
